spring.application.name=quanlysinhvien

spring.datasource.url=jdbc:h2:mem:quanlysinhvien;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# Khai báo rõ Dialect của SQL Server để Hibernate sinh đúng cú pháp T-SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Chỉ kiểm tra cấu hình hoặc tắt tự động sửa bảng đã tồn tại
spring.jpa.hibernate.ddl-auto=none
# Thông tin kết nối SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123123

# Cấu hình Hibernate (Tự động cập nhật bảng)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

